### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by wkloucek** [owncloud/cs3api-validator#1]
# Test strategy
This test suite shall provide E2E tests for CS3API implementations. Currently we will test the behavior of REVA / oCIS.

Other implementations of the CS3API can then use this as a benchmark to see how they comply to the reference implementation REVA.

# First steps

To get this going we currently limit the scope:

## Set up infra for testing:
- oCIS or REVA as system-under-test, expose Gateway port only (9142, in the case of oCIS)
- see how to provision users (REVA needs LDAP, oCIS has OCS api but we shouldn't use it!?)
- [godog](https://github.com/cucumber/godog) as Gherkin testing framework #2 

## WOPI server usecase
- test CS3API calls which are also done by the [CS3API WOPI server](https://github.com/cs3org/wopiserver)
- test with user authentication (basic auth or OIDC??) and public auth (public link authentication)
- test with the oCIS storage

# Timeline
- 22. Dec 2021: kickoff meeting
- kalendar week 52 2021: @wkloucek will look into a first setup
- Jan 2022: discussion on the first setup @micbar @phil-davis @individual-it @ScharfViktor @wkloucek

**Comment by micbar** [comment]
IMO we should not provision or deprovision users in this test suite
We create and delete storage spaces.

**Comment by wkloucek** [comment]
> IMO we should not provision or deprovision users in this test suite We create and delete storage spaces.

For authenticated requests we cannot work around having a user context. Therefore we need to see where the users come from (currently this will be LDAP)

**Comment by wkloucek** [comment]
Or there is a way to have a static users / group driver.. But we somehow need users.

**Comment by micbar** [comment]
let us use static users/groups from LDAP

**Comment by individual-it** [comment]
we could use ocs through the testing-middleware to provision users.
If the system is to be used for an other implementation then a similar testing middleware would be needed to provision users in whatever way that implementation does it
that would give an extra layer of complexity, so maybe for the start a static list of users would do

**Comment by phil-davis** [comment]
> let us use static users/groups from LDAP

yes, when can require that the implementation-under-test already has a known set of users, groups and group memberships. The tests can make use of those. We will have to think about how to "cleanup" at the end of scenarios - but that should just be a matter of deleting resources (files/folders in user's personal area, and deleting any other resources that might have been created by a scenario (spaces... if they can exist)

**Comment by micbar** [comment]
First Implementation is finished by #3
